kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: podloveradiator
    password:
      from_secret: docker_password
    repo: podlove/radiator-cms
    tags: latest
    dockerfile: app/dockerfile
  when:
    branch:
    - master
    - develop
