query audio($id: ID!) {
  audio(id: $id) {
    audioFiles {
      byteLength,
      file,
      id
      mimeType,
      title
    },
    audioPublication {
      id,
      publishState,
      publishedAt,
      title
    },
    chapters {
      image,
      link,
      start,
      startString,
      title
    },
    contributions {
      contributionRole {
        id,
        title
      },
      id,
      person {
        displayName,
        id,
        image,
        name,
        nick
      },
      position
    },
    duration,
    durationString,
    episodes {
      id,
      podcast {
        id,
        title
      },
      title
    },
    id,
    image,
    title
  }
}