query episode($id: ID!) {
  episode(id: $id) {
    audio {
      audioFiles {
        byteLength,
        mimeType,
        title
      },
      chapters {
        image,
        link,
        start,
        startString,
        title
      },
      duration,
      durationString,
      id
    },
    guid,
    id,
    # image,
    isPublished,
    number,
    podcast {
    	title
  	},
    publishedAt,
    shortId,
    slug,
    subtitle,
    summary,
    summaryHtml,
    summarySource,
    title
  }
}
