query episode($id: ID!) {
  episode(id: $id) {
    audio {
      audioFiles {
        byteLength,
        direct_url,
        id,
        mimeType,
        title
      },
      chapters {
        image,
        link,
        start,
        startString,
        title
      },
      duration,
      durationString,
      id,
      image
    },
    guid,
    id,
    image,
    number,
    podcast {
      id,
    	title
  	},
    publicPage,
    publishState,
    publishedAt,
    shortId,
    slug,
    subtitle,
    summary,
    summaryHtml,
    title
  }
}
