query feedInfo($url: String!){
  feedInfo(url: $url){
    title,
    suggestedShortId,
    subtitle,
    link,
    image,
    feeds {
     	title,
    	enclosureType,
      episodes {
        title
      }
    }
  }
}
