{
  networks {
    id,
    image,
    podcasts {
      episodes(itemsPerPage: 5, page: 1) {
        guid,
        id,
        image,
        isPublished,
        number,
        publishedAt,
        shortId,
        slug,
        subtitle,
        summary,
        summaryHtml,
        summarySource,
        title
      },
      id,
      image,
      slug,
      subtitle,
      title,
    },
    slug,
    title
  }
}