query network($id: ID!) {
  network(id: $id) {
    audioPublications {
      audio {
        audioFiles {
          byteLength,
          directUrl,
          id,
          mimeType,
          title
        },
        chapters {
          duration,
          durationString,
          image,
          link,
          start,
          startString,
          title
        },
        contributions {
          contributionRole {
            id,
            isPublic,
            title
          },
          id,
          person {
            displayName,
            email,
            id,
            link,
            name,
            nick
          },
          position
        },
        duration,
        durationString,
        id,
        image
      },
      id,
      publishState,
      publishedAt,
      title
    },
    collaborators {
      permission,
      user {
        displayName,
        email,
        image,
        username
      }
    },
    id,
    image,
    people {
      displayName,
      email,
      id,
      link,
      name,
      nick
    },
    podcasts {
      author,
      episodes(itemsPerPage: 5, page: 1) {
        guid,
        id,
        image,
        number,
        publicPage,
        publishState,
        publishedAt,
        shortId,
        slug,
        subtitle,
        summary,
        summaryHtml,
        title
      },
      episodesCount,
      id,
      image,
      language,
      lastBuiltAt,
      ownerEmail,
      ownerName,
      publicPage,
      publishState,
      publishedAt,
      publishedFeeds {
        enclosureMimeType,
        feedUrl
      },
      slug,
      shortId,
      subtitle,
      summary,
      title
    },
    slug,
    title
  }
}
