{
  podcasts {
    author,
    description,
    episodes(itemsPerPage: 200, page: 1) {
      content,
      description,
      duration,
      guid,
      id,
      image,
      number,
      publishedAt,
      slug,
      subtitle,
      title,
    },
    id,
    language,
    lastBuiltAt,
    ownerEmail,
    ownerName,
    publishedAt,
    slug,
    subtitle,
    title,
  }
}