query podcast($id: ID!) {
  podcast(id: $id) {
    author,
    contributions {
      contributionRole {
        id,
        isPublic,
        title
      },
      id,
      person {
        displayName,
        email,
        id,
        link,
        name,
        nick
      },
      position
    },
    episodes(
      itemsPerPage: 200,
      page: 1
    ) {
      audio {
        audioFiles {
          byteLength,
          direct_url,
          id,
          mimeType,
          title
        },
        chapters {
          image,
          link,
          start,
          startString,
          title
        },
        duration,
        durationString,
        id,
        image
      },
      guid,
      id,
      number,
      publicPage,
      publishState,
      publishedAt,
      shortId,
      slug,
      subtitle,
      summary,
      summaryHtml,
      title
    },
    episodesCount,
    id,
    image,
    language,
    lastBuiltAt,
    ownerEmail,
    ownerName,
    publicPage,
    publishState,
    publishedAt,
    publishedFeeds {
      enclosureMimeType,
      feedUrl
    },
    slug,
    shortId,
    subtitle,
    summary,
    title
  }
}
