{
  podcasts {
    author,
    episodes(itemsPerPage: 200, page: 1) {
      guid,
      id,
      image,
      isPublished,
      number,
      publishedAt,
      shortId,
      slug,
      subtitle,
      summary,
      summaryHtml,
      summarySource,
      title
    },
    episodesCount,
    id,
    language,
    lastBuiltAt,
    ownerEmail,
    ownerName,
    publishedAt,
    slug,
    subtitle,
    summary,
    title,
  }
}