query podcast($id: ID!) {
  podcast(id: $id) {
    author,
    contributions {
      contributionRole {
        id,
        isPublic,
        title
      },
      id,
      person {
        displayName,
        email,
        id,
        link,
        name,
        nick
      },
      position
    },
    episodes(
      itemsPerPage: 200,
      page: 1
    ) {
      guid,
      id,
      image,
      isPublished,
      number,
      publishedAt,
      shortId,
      slug,
      subtitle,
      summary,
      summaryHtml,
      summarySource,
      title
    },
    episodesCount,
    id,
    image,
    isPublished,
    language,
    lastBuiltAt,
    ownerEmail,
    ownerName,
    publishedAt,
    slug,
    shortId,
    subtitle,
    summary,
    title,
  }
}